language: generic
if: "(type = push AND branch IN (master, develop)) OR type IN (pull_request, api, cron)"
jdk:
- openjdk8
services:
- docker
before_install:
- curl -L https://dl.bintray.com/snowplow/snowplow-generic/data_structures_ci_0.3.1.zip | jar xv && chmod +x ./data-structures-ci

jobs:
  include:
  - stage: Test
    name: Unit Tests
    script: echo "Pretending to run unit tests..."
  - name: Integration Tests
    script: echo "Pretending to run integration tests..."
  - stage: Build
    name: Build
    script: echo "Pretending to build and push artifacts..."
  - stage: Deployment Requirements
    if: branch IN (master, develop)
    name: Check Deployment Requirements
    env:
    - ENV=$([[ $TRAVIS_BRANCH == 'master' ]] && echo 'PROD' || echo 'DEV') 
    script:
    - echo "Environment is $ENV"
    - './data-structures-ci check --manifestPath $TRAVIS_BUILD_DIR/snowplow-schemas.json
      --username $SNOWPLOW_USERNAME --password $SNOWPLOW_PASSWORD --environment $ENV 2>/dev/null'
  - stage: Deploy
    if: type = push AND branch IN (master, develop)
    name: Deployment
    script: echo "Prepare deployment..."
    deploy:
      skip_cleanup: true
      provider: script
      script: echo "Pretending to deploy..."
      on:
        condition: type = push AND branch IN (master, develop)
  