name: ci

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
    - uses: actions/checkout@v2
    
    - name: Unit Tests
      run: echo "Pretending to run unit tests..."

    - name: Integration Tests
      run: echo "Pretending to run integration tests..."

    - name: Build
      run: echo "Pretending to build artifacts..."

    - name: Release
      run: echo "Pretending to push artifacts..."
  
  deploy-requirements:
    runs-on: ubuntu-latest
    name: Verify deployment requirements
    if: (github.event_name == 'pull_request' && (github.base_ref == 'master' || github.base_ref == 'develop')) || (github.event_name == 'push' && (github.ref == 'master' || github.ref == 'develop'))

    steps:
    - uses: actions/checkout@v2
    
    - name: Extract branch and environment
      run: |
        BRANCH=$([[ $GITHUB_EVENT_NAME == 'pull_request' ]] && echo $GITHUB_BASE_REF || echo $GITHUB_REF)
        ENV=$([[ $BRANCH == 'master' ]] && echo 'PROD' || echo 'DEV')
        echo "Target branch is $BRANCH"
        echo "Target environment is $ENV"
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
        echo "ENV=$ENV" >> $GITHUB_ENV
        
    - name: Run Snowplow's Data Structures CI
      uses: snowplow-product/msc-schema-ci-action/check@v1
      with:
        organization-id: ${{ secrets.SNOWPLOW_ORG_ID }}
        api-key: ${{ secrets.SNOWPLOW_API_KEY }}
        manifest-path: snowplow-schemas.json
        environment: ${{ env.ENV }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    if: github.event_name == 'push' && (github.ref == 'master' || github.ref == 'develop')
    needs: [ build, deploy-requirements ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Deploy
      run: echo "Pretending to deploy to $ENV..."